sudo: required
services:
  - docker

before_install:
  - docker build -t asetk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asetk/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-udemy"
  env: "dockerreactudemy-env"
  bucket_name: "elasticbeanstalk-us-east-2-058664351348"
  bucket_path: "docker-react-udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY