version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules  #We do NOT need copy(in Dockerfile) files that we mounted as volume. But we can, no errors.
      - .://home/node/app
  tests: #Second service of the same image. But here we do not run default "start" command, we will run "test" command to run tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules  #We do NOT need copy(in Dockerfile) files that we mounted as volume. But we can, no errors.
      - .://home/node/app
    command: ["npm", "run", "test"]
